name: Assign Bot

on:
  issue_comment:
    types: [created]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Assign the issue if comment is "bot/assign"
        if: contains(github.event.comment.body, 'bot/assign')
        uses: actions-ecosystem/action-assign@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.event.comment.user.login }}

      - name: Comment on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: '⚠️ Unable to assign the issue. This could be due to permissions or other issues.'
            })
