name: ESLint Check

on:
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install client dependencies
      - name: Install client dependencies
        run: |
          cd client
          npm ci

      # Run ESLint on client
      - name: Run ESLint on client
        run: |
          cd client
          npx eslint . --max-warnings=0

      # Install server dependencies
      - name: Install server dependencies
        run: |
          cd server
          npm ci

      # Run ESLint on server
      - name: Run ESLint on server
        run: |
          cd server
          npx eslint . --max-warnings=0
