name: ESLint Check

on:
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .
        # If you want to automatically fix linting issues, use the following line instead:
        # run: npx eslint . --fix 
        # Note: Using --fix will modify files, which may not be desirable in a CI context.
