name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR description
        run: |
          BODY="${{ github.event.pull_request.body }}"

          echo "Checking PR body..."
          
          # Check for issue reference (e.g. Fixes #123)
          if ! echo "$BODY" | grep -qE "(Fixes|Closes|Resolves) #[0-9]+"; then
            echo "PR must reference an issue (e.g., Fixes #123)."
            exit 1
          fi

          echo "✅ PR description is valid."
